server:
  port: 8005
spring:
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password:
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
website:
  domain-name: www.sn.com